name: C Program CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT: simple-gui-text-editor # Manually specify the project name here

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GCC and necessary build tools
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install build-essential -y

      # Compile the C program using the PROJECT environment variable
      - name: Compile C Program
        run: |
          gcc index.c src/$PROJECT/*.c src/shared/*.c -o index

      # Run the compiled program
      - name: Run Program
        run: ./index
