name: C Program CI - first-editor

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GCC and necessary build tools
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install build-essential -y

      # Compile the C program (specific project + shared folder)
      - name: Compile C Program
        run: |
          gcc src/first-editor/*.c src/shared/*.c -o first-editor

      # Run the compiled program
      - name: Run Program
        run: ./first-editor
